### ISSUE TITLE
Error - It would be nice to have some examples of this actually in use with FABRIC

### ISSUE THREAD

**Issue by sedetweiler** [chrisgoringe/cg-image-picker#25] opened 2023-10-06 04:23 UTC
Error occurred when executing Latent Chooser:

list index out of range

File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\cg-image-picker\image_chooser.py", line 108, in func
latent[key] = latents[key][i].unsqueeze(0)

**Comment by chrisgoringe** [comment] 2023-10-06 05:03
Really helpful if you can save a workflow with a bug report...

**Comment by sedetweiler** [comment] 2023-10-06 14:21
If I can get this to even remotely work, then it would be worth it.  But this graph is just a wreck as there was not real example to start with for troubleshooting.  Once it has a bit more time out there and some examples exist, then I can return to this and get a video up on its use.  I am also assuming the trigger would fire when I select an image in the preview, but that doesn't appear to work.  I know this UI is a hard one to make friendly, it has to be a huge challenge for you, but keep on working at it, as I think this has a lot of promise.

**Comment by chrisgoringe** [comment] 2023-10-07 00:13
Closing this as effectively a duplicate of #7 - I'll get to it!

**Closed by chrisgoringe** 2023-10-07 00:13 UTC
