### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by filliptm** [chrisgoringe/cg-image-picker#84] opened 2024-03-07 11:42 UTC
can we have the picker node hold the cache of what you previously picked? having to select the images every time you run the workflow REALLY bogs things down, especially if you workflow is large and the node is near the beginning, it forces the whole workflow after to have to be rerun every time

**Comment by LiJT** [comment] 2024-03-08 13:19
yeah I second that, everytime I click queue prompt, i have to reselect things from the begining, and it kept re-run thing that I have selected for some wierd reason... So far I have to go back to "select Latent from batch" to do a smooth workflow...This workflow is awesome! Really wish it can remember the cache!

**Comment by LiJT** [comment] 2024-03-08 13:20
![image](https://github.com/chrisgoringe/cg-image-picker/assets/11270197/21f4d218-84ce-46aa-90c4-ff170a32bb50)
this was my half ass solution to replace image picker to prevent it re-run the whole calculation

**Comment by chrisgoringe** [comment] 2024-03-08 22:43
Sorry, I don't understand what's being asked for here? Can someone describe:

(a) what you do
(b) what currently happens
(c) what you would like to happen

And, if possible, provide the simplest possible workflow that illustrates the problem

**Comment by filliptm** [comment] 2024-03-10 17:41
Put simply, we'd like the node to have a memory of what you've already selected. If nothing changes down the workflow, like seed or settings, the node in its current state still requires you to select a choice. We'd like to the node to remember your choice if i hit que again and nothing has changed up to the preview chooser node

that way when we click que again we do not have to select an image in the node over and over

**Comment by chrisgoringe** [comment] 2024-03-10 20:04
But what if you want to repeat the lower part of the workflow with a different selection?

**Comment by filliptm** [comment] 2024-03-10 20:06
i dont think re running the ksampler is a bad trade off. That or add a toggle on the node itself, what ever solution you think is best, but as it stands your node is unusable in larger workflows for the reason that it doesnt hold a memory at all of selection. In my humble opinion

**Comment by chrisgoringe** [comment] 2024-03-10 20:13
Really? Having to rerun the upstream section (which might be much more than just a ksampler) is better than having to click an image? I'm obviously not understanding the problem (doesn't help that you haven't actually shared a workflow or screenshot or anything like that...)

**Comment by filliptm** [comment] 2024-03-10 20:25
thats what im saying. if your node is anywhere near the beginning, regardless of size of flow afterwords, EVERYTHING has to rerun after the node, if i want to select a new image starting from your node, i dont think its unreasonable to rerun that section if i want a new choice imo, as your going to have to rerun everything afterwords anyway
<img width="1152" alt="Untitled" src="https://github.com/chrisgoringe/cg-image-picker/assets/55672949/c23f7163-cdc5-420c-94bb-e372e7ab8909">

**Comment by chrisgoringe** [comment] 2024-03-10 20:57
Let me see if I understand - the problem isn't that you need to click the images in the image chooser node again, it's that nodes downstream of the chooser have to rerun even though they are getting the same input (because the chooser node reruns).

OK, that makes sense.

So if I could add an option (maybe "Resend previous output") that, as long as nothing upstream of the chooser had changed, would prevent the chooser from running (and treat it as unchanged), would that solve the problem?

**Comment by filliptm** [comment] 2024-03-10 21:59
correct, thats the issue

yeah that would be perfect! i know a lot of people will be happy with that added feature

**Comment by chrisgoringe** [comment] 2024-03-12 12:11
I just pushed an update that I think does what you want - select `repeat last selection` as the mode.

If there is no previous selection, or if anything *upstream* has changed, it acts as if it were `Always pause`. But if there are no upstream changes, it is marked as not changed. 

Hopefully ComfyUI will take care of the rest.

**Comment by LiJT** [comment] 2024-03-12 14:35
![image](https://github.com/chrisgoringe/cg-image-picker/assets/11270197/ed3f77c8-199d-4209-b5f8-0cb233adc907)

Hello! Thank you Chris for this fast update! Its working great for having one image chooser only so far, but if two are added, only the very first image chooser working, if the second one has a different setting than the first chooser, It will not work and no image being previewed.... Hopefully this can support multi-chooser in one workflow, this will be amazing!! Thank you in advance!

**Comment by chrisgoringe** [comment] 2024-03-13 06:05
try it now

**Comment by RassilonSleeps** [comment] 2024-03-15 08:24
> try it now

'Repeat last selection' works for me now across a chain of 3 preview chooser

**Closed** 2024-03-15 08:43 UTC
Labels: believe fixed

**Comment by gshawn3** [comment] 2024-04-18 06:56
Thank you very much for adding this! I couldn't figure out why my ComfyUI cache was being invalidated downstream even when I picked the same images in the Image Chooser. The Repeat Last Selection mode works much better.
